dependencies:
  - python=3.12.*
  - numpy=2.3.2
  - pip
  - pip:
    - affine==2.4.0
    - attrs==25.3.0
    - certifi==2025.8.3
    - click==8.2.1
    - click-plugins==1.1.1.2
    - cligj==0.7.2
    - contourpy==1.3.3
    - cycler==0.12.1
    - fonttools==4.59.0
    - geopandas==1.1.1
    - joblib==1.5.1
    - kiwisolver==1.4.8
    - matplotlib==3.10.5
    - packaging==25.0
    - pandas==2.3.1
    - pillow==11.3.0
    - pyogrio==0.11.1
    - pyparsing==3.2.3
    - pyproj==3.7.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - raster-footprint==0.2.0
    - rasterio==1.4.3
    - scikit-learn==1.7.1
    - scipy==1.16.1
    - seaborn==0.13.2
    - shapely==2.1.1
    - six==1.17.0
    - threadpoolctl==3.6.0
    - tzdata==2025.2
    - git+https://github.com/hydroshare/nbfetch.git@v0.6.4
