name: workshop
channels:
  - conda-forge

dependencies:
  - python=3.11
  - sqlite>=3.35
  - satpy
  - pyresample
  - pyspectral
  - cartopy
  - matplotlib
  - xarray
  - dask
  - numpy
  - h5py
  - netcdf4
  - rasterio
  - jupyterlab
  - ipywidgets
  - pip
  - pip:
    - git+https://github.com/hydroshare/nbfetch.git@v0.6.4
