#!/bin/bash
set -euo pipefail

# install nbfetch
jupyter server extension enable --py nbfetch --sys-prefix

# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh

# install pixi
curl -fsSL https://pixi.sh/install.sh | bash

# add pixi and uv to PATH
echo 'export PATH="/root/.pixi/bin:/root/.local/bin:${PATH}"' >>~/.bashrc

