#!/bin/bash
set -euo pipefail

jupyter labextension install @axlair/jupyterlab_vim

# Update custom Jupyter Lab settings
cd /home/jovyan/.jupyter/lab/user-settings/@axlair/jupyterlab_vim
sed -i 's/"enabled": true/"enabled": false/g' plugin.jupyterlab-settings